### ISSUE TITLE
Cycle detection

### ISSUE THREAD

**Issue by goodmami** [xigt/xigt#30]
A file like this results in a recursive cycle when resolving the item's value:

```xml
<xigt-corpus>
    <igt>
        <tier type="words" id="a" segmentation="a">
            <item id="a1" segmentation="a1"/>
        </tier>
    </igt>
</xigt-corpus>
```

Currently only query.descendants() has cycle detection. Make sure the other alignment expression resolution functions do, too.

**Comment by curtosis** [comment]
query.ancestors() definitely needs cycle detection; it will loop forever on e.g. resolving children in phrase structure tiers.

**Comment by goodmami** [comment]
@curtosis, thanks for the comment, and sorry for my late response. Did you come across this problem in real data? If so, can you share a problematic example instance?
