### ISSUE TITLE
Check that XC is a Corpus in xigtxml.dump()

### ISSUE THREAD

**Issue by rgeorgi** [xigt/xigt#31]
I confused myself recently by trying to dump an Igt instance with xigtxml.dump() and receiving an exception about the Igt instance not having metadata attribute.

Eventually, I realized this was because I was trying to dump an instance rather than a corpus, but this might be something that would benefit from an explicit type-check.

**Comment by goodmami** [comment]
Yes, a check would be a good idea. This is an easy fix ; I'll do it for the next version.
