### ISSUE TITLE
Consider publishing your code in JOSS!

### ISSUE THREAD

**Issue by jkahn** [xigt/xigt#45]
Hi XIGT people! Consider whether you want to release this library in the [Journal of Open Source Software](http://joss.theoj.org/about)! Getting code published in a cite-able form might help you elsewhere as you go along.

**Comment by goodmami** [comment]
@jkahn thanks for the pointer! We already have some citable publications about Xigt (e.g. http://link.springer.com/article/10.1007/s10579-014-9276-1). Is it still worth submitting to JOSS?

(although I have at least one other library of significant size that doesn't have a publication, to which this may be better suited: https://github.com/delph-in/pydelphin)

**Comment by goodmami** [comment]
Closing this issue since it seems there's less of a need given that we already have a publication or two to point to.
